/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.EnderecoService;
import dao.AlunoDAO;
import dto.EnderecoDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Aluno;

/**
 *
 * @author joaoc
 */
public class ViewCadastroAluno extends javax.swing.JFrame {
    private AlunoDAO alunoDao = new AlunoDAO();
    private boolean alunoPesquisado;
    private ArrayList<Aluno> lista;
    /**
     * Creates new form ViewCadastroAluno
     */
    public ViewCadastroAluno() {
        initComponents();
        atualizaGrid();
    }
    
    public void atualizaGrid(){
        try {
            String sql = "SELECT * FROM public.\"Aluno\" ORDER BY \"RA_ALUNO\";"; 
            lista = new ArrayList<>();
            lista = alunoDao.retornaLista(sql);
            
            //Manipulação de tabela
            tbCadastroAluno.removeAll();
            
            DefaultTableModel tableModel = new DefaultTableModel(new Object[][]{}, new String[]{"RA", "Nome", "Dt. Nascimento"}){
                  @Override
                  public boolean isCellEditable(int row, int column){
                      return false;
            }
        };
            
            //seta as colunas na tabela
            tbCadastroAluno.setModel(tableModel);
            
            //Adiciona as linhas as tabelas com os dados dos alunos
            DefaultTableModel dm = (DefaultTableModel)tbCadastroAluno.getModel();
            for(Aluno aluno : lista){
                dm.addRow(new Object[]{aluno.getRa(), aluno.getNome(), aluno.getData_nasc()});
            }
           
            tbCadastroAluno.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e){
                    int LinhaSelecionada = tbCadastroAluno.getSelectedRow();
                    if(LinhaSelecionada != -1){
                              mostrarAluno(lista.get(LinhaSelecionada));
                    }
                }
            });
        } catch (Exception e) {
        }
    }
    
        public void limparCampos(){
            tfRaAluno.setText("");
            tfNomeAluno.setText("");
            tfDataNascimentoAluno.setText("");
            tfRaAluno.setEditable(true);
            btSalvar.setEnabled(true);
        }
    
        private void mostrarAluno(Aluno aluno){
            tfRaAluno.setText(String.valueOf(aluno.getRa()));
            tfNomeAluno.setText(aluno.getNome());
            tfDataNascimentoAluno.setText(aluno.getData_nasc());
            tfRaAluno.setEditable(false);
            btSalvar.setEnabled(false);
            alunoPesquisado = true;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jLabel1 = new javax.swing.JLabel();
                    jPanel1 = new javax.swing.JPanel();
                    jLabel2 = new javax.swing.JLabel();
                    tfRaAluno = new javax.swing.JTextField();
                    jLabel3 = new javax.swing.JLabel();
                    tfNomeAluno = new javax.swing.JTextField();
                    jLabel4 = new javax.swing.JLabel();
                    tfDataNascimentoAluno = new javax.swing.JFormattedTextField();
                    jScrollPane1 = new javax.swing.JScrollPane();
                    tbCadastroAluno = new javax.swing.JTable();
                    btPesquisar = new javax.swing.JButton();
                    btAtualizar = new javax.swing.JButton();
                    btRemover = new javax.swing.JButton();
                    btSalvar = new javax.swing.JButton();
                    tfCep = new javax.swing.JTextField();
                    jLabel5 = new javax.swing.JLabel();
                    jLabel6 = new javax.swing.JLabel();
                    tfLogradouro = new javax.swing.JTextField();
                    jLabel7 = new javax.swing.JLabel();
                    tfBairro = new javax.swing.JTextField();
                    tfCidadeUf = new javax.swing.JTextField();
                    jLabel8 = new javax.swing.JLabel();
                    tfNumero = new javax.swing.JTextField();
                    jLabel9 = new javax.swing.JLabel();

                    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel1.setText("Cadastro de Alunos");

                    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                    jLabel2.setText("R.A:");

                    jLabel3.setText("Nome:");

                    jLabel4.setText("Data de Nascimento:");

                    tfDataNascimentoAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(tfRaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(jLabel3)
                                                  .addComponent(tfNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addComponent(tfDataNascimentoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addContainerGap())
                    );
                    jPanel1Layout.setVerticalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                  .addComponent(jLabel2)
                                                  .addComponent(jLabel3)
                                                  .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                  .addComponent(tfRaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(tfNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(tfDataNascimentoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(16, Short.MAX_VALUE))
                    );

                    tbCadastroAluno.setModel(new javax.swing.table.DefaultTableModel(
                              new Object [][] {
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null},
                                        {null, null, null, null}
                              },
                              new String [] {
                                        "Title 1", "Title 2", "Title 3", "Title 4"
                              }
                    ));
                    jScrollPane1.setViewportView(tbCadastroAluno);

                    btPesquisar.setText("Pesquisar");
                    btPesquisar.setPreferredSize(new java.awt.Dimension(100, 23));

                    btAtualizar.setText("Atualizar");
                    btAtualizar.setPreferredSize(new java.awt.Dimension(100, 23));
                    btAtualizar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        btAtualizarActionPerformed(evt);
                              }
                    });

                    btRemover.setText("Remover");
                    btRemover.setPreferredSize(new java.awt.Dimension(100, 23));
                    btRemover.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        btRemoverActionPerformed(evt);
                              }
                    });

                    btSalvar.setText("Salvar");
                    btSalvar.setPreferredSize(new java.awt.Dimension(100, 23));
                    btSalvar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        btSalvarActionPerformed(evt);
                              }
                    });

                    tfCep.addKeyListener(new java.awt.event.KeyAdapter() {
                              public void keyPressed(java.awt.event.KeyEvent evt) {
                                        tfCepKeyPressed(evt);
                              }
                    });

                    jLabel5.setText("Cep");

                    jLabel6.setText("Logradouro");

                    jLabel7.setText("Bairro");

                    jLabel8.setText("Cidade/UF");

                    jLabel9.setText("N*");

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addContainerGap()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                          .addComponent(jLabel5)
                                                                                          .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                          .addComponent(jLabel6))
                                                                                .addGap(170, 170, 170)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                          .addGroup(layout.createSequentialGroup()
                                                                                                    .addComponent(jLabel7)
                                                                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                                                          .addComponent(tfBairro)))
                                                                      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                      .addComponent(jScrollPane1)))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                .addGap(14, 14, 14)
                                                                                .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                .addContainerGap(12, Short.MAX_VALUE)
                                                                                .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addGap(48, 48, 48)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                          .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                          .addComponent(jLabel9))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                          .addComponent(tfCidadeUf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                          .addComponent(jLabel8))
                                                                                .addGap(0, 2, Short.MAX_VALUE))
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                        .addContainerGap())
                    );
                    layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel5)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addComponent(tfCidadeUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                      .addComponent(jLabel8)
                                                                      .addComponent(jLabel9))
                                                            .addGap(28, 28, 28)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel6)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel7)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                    );

                    pack();
          }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
              
              if(alunoPesquisado){
                        Aluno aluno = new Aluno();
                        aluno.setRa(Integer.parseInt(tfRaAluno.getText()));
                        aluno.setNome(tfNomeAluno.getText());
                        aluno.setData_nasc(tfDataNascimentoAluno.getText());

                        if(alunoDao.atualizar(aluno)){
                                  JOptionPane.showMessageDialog(this,"Aluno atualizado com sucesso!");
                                  limparCampos();
                                  atualizaGrid();
                        }else{
                                  JOptionPane.showMessageDialog(this,"Erro ao atualizar o aluno, solicite suporte técnico!", "Erro", 
                                          JOptionPane.ERROR_MESSAGE);
                        }
              }else{
                        JOptionPane.showMessageDialog(this,"Selecione um aluno para Atualizar!", "Atenção", 
                                JOptionPane.WARNING_MESSAGE);
              }

    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
                    Aluno aluno = new Aluno();
                    aluno.setRa(Integer.parseInt(tfRaAluno.getText()));
                    aluno.setNome(tfNomeAluno.getText());
                    aluno.setData_nasc(tfDataNascimentoAluno.getText());

                    if(alunoDao.salvar(aluno)){
                              JOptionPane.showMessageDialog(this, "Aluno salvo com sucesso!", "Sucesso",JOptionPane.PLAIN_MESSAGE);
                    }else{
                              JOptionPane.showMessageDialog(this, "Erro ao salvar aluno, solicite suporte!", "Erro",JOptionPane.PLAIN_MESSAGE);

                    atualizaGrid();
                    limparCampos();
                    }
    }//GEN-LAST:event_btSalvarActionPerformed

          private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
                    
                    if(alunoPesquisado){
                              alunoDao.delete(Integer.parseInt(tfRaAluno.getText()), "tbCadastroAluno",  "RA_ALUNO");
                                  JOptionPane.showMessageDialog(this,"Aluno removido com sucesso!");
                                  limparCampos();
                                  atualizaGrid();
                    }else{
                              JOptionPane.showMessageDialog(this,"Selecione um aluno para Remover!", "Atenção", 
                                JOptionPane.WARNING_MESSAGE);
                    }
          }//GEN-LAST:event_btRemoverActionPerformed

          private void tfCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCepKeyPressed
                   if(evt.getKeyCode() == evt.VK_ENTER){
                             if(!tfCep.getText().equals("")){
                                       try {
                                                 EnderecoDTO endereco = EnderecoService.buscaEndereco(tfCep.getText());
                                                 tfLogradouro.setText(endereco.getLogradouro());
                                                 tfBairro.setText(endereco.getBairro());
                                                 tfCidadeUf.setText(endereco.getLocalidade() + " / " + endereco.getUf());

                                       } catch (Exception ex) {
                                                 Logger.getLogger(ViewCadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
                                       }
                             }
                   }
          }//GEN-LAST:event_tfCepKeyPressed

   

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JButton btAtualizar;
          private javax.swing.JButton btPesquisar;
          private javax.swing.JButton btRemover;
          private javax.swing.JButton btSalvar;
          private javax.swing.JLabel jLabel1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JLabel jLabel3;
          private javax.swing.JLabel jLabel4;
          private javax.swing.JLabel jLabel5;
          private javax.swing.JLabel jLabel6;
          private javax.swing.JLabel jLabel7;
          private javax.swing.JLabel jLabel8;
          private javax.swing.JLabel jLabel9;
          private javax.swing.JPanel jPanel1;
          private javax.swing.JScrollPane jScrollPane1;
          private javax.swing.JTable tbCadastroAluno;
          private javax.swing.JTextField tfBairro;
          private javax.swing.JTextField tfCep;
          private javax.swing.JTextField tfCidadeUf;
          private javax.swing.JFormattedTextField tfDataNascimentoAluno;
          private javax.swing.JTextField tfLogradouro;
          private javax.swing.JTextField tfNomeAluno;
          private javax.swing.JTextField tfNumero;
          private javax.swing.JTextField tfRaAluno;
          // End of variables declaration//GEN-END:variables
}
